<error errorId="08095130-a80f-47bc-842f-ad6517216183" host="SF-D001" type="System.ArgumentOutOfRangeException" message="Year, Month, and Day parameters describe an un-representable DateTime." source="mscorlib" detail="System.ArgumentOutOfRangeException: Year, Month, and Day parameters describe an un-representable DateTime.&#xD;&#xA;   at System.DateTime.DateToTicks(Int32 year, Int32 month, Int32 day)&#xD;&#xA;   at System.DateTime..ctor(Int32 year, Int32 month, Int32 day)&#xD;&#xA;   at CHM.Services.Utils.DateTimeExtensions.isValidDate(Int32 date, Int32 month, Int32 year) in E:\Enthusis_Latest\Enthusis.Services\CHM.Services\CHM.Services\Utils\Utils.cs:line 52&#xD;&#xA;   at CHM.Services.Utils.DateTimeExtensions.GetDateForWeekDay(DayOfWeek DesiredDay, Int32 Occurrence, Int32 Month, Int32 Year) in E:\Enthusis_Latest\Enthusis.Services\CHM.Services\CHM.Services\Utils\Utils.cs:line 41&#xD;&#xA;   at CHM.Services.Controllers.InterventionsController.&lt;GenerateInterventions&gt;d__1.MoveNext() in E:\Enthusis_Latest\Enthusis.Services\CHM.Services\CHM.Services\Controllers\InterventionsController.cs:line 246&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Threading.Tasks.TaskHelpersExtensions.&lt;CastToObject&gt;d__3`1.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.ApiControllerActionInvoker.&lt;InvokeActionAsyncCore&gt;d__0.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.ActionFilterResult.&lt;ExecuteAsync&gt;d__2.MoveNext()&#xD;&#xA;--- End of stack trace from previous location where exception was thrown ---&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)&#xD;&#xA;   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)&#xD;&#xA;   at System.Web.Http.Controllers.ExceptionFilterResult.&lt;ExecuteAsync&gt;d__0.MoveNext()" user="samathareddy216@gmail.com" time="2016-12-30T10:15:10.0089132Z" />